### ISSUE TITLE
TODO: enhance this project

### ISSUE THREAD

**Issue by slafs** [slafs/sentry-docker#1]
There are some future plans for this repo:
- [x] add LDAP support
- [x] maintain a changelog
- [x] implement and document other Sentry settings
- [x] provide a Contribution guidelines for possible contributors and update README about the main goals.
